
NumPy
Задание 1
1. Импортируйте библиотеку Numpy и дайте ей псевдоним np. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 не включительно Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк). Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [6]:
import numpy as np


In [7]:

a = np.arange(12, 24)
print(a)


[12 13 14 15 16 17 18 19 20 21 22 23]


In [8]:
a.reshape(3, 4)


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a.reshape(4, 3)


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a.reshape(2, 6)


array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a.reshape(6, 2)


array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
a.resize(12, 1)
print(a)


[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [13]:
a.reshape(-1, 3)


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
np.reshape(a, (-1, 6))


array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
np.reshape(a, (-1, 2))


array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [16]:
a.reshape(4, -1)


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
a.reshape(12, -1)


array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [18]:
a.ndim


2

2. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [19]:
a = np.random.randn(3, 4)
print(a)

[[ 0.94792277 -0.72094827 -0.19432071 -1.20023022]
 [ 1.60060237 -0.2594095  -0.24478527  0.21828477]
 [ 0.09789486  0.21146613  0.58488527 -0.80766267]]


In [20]:
b = a.flatten()
print(b)

[ 0.94792277 -0.72094827 -0.19432071 -1.20023022  1.60060237 -0.2594095
 -0.24478527  0.21828477  0.09789486  0.21146613  0.58488527 -0.80766267]


In [21]:
a.size == b.size

True

3. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?

In [22]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [23]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [24]:
np.array_equal(a, b)

True


4. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [25]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
print('Массив a ', a, sep='\n')
print('Массив b ', b, sep='\n')

Массив a 
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Массив b 
[[1. 1.]
 [1. 1.]]


In [26]:
v = np.concatenate((a, b), axis = 0)
print(v)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [27]:

v.size

10


5. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [28]:

a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
At = A.transpose()
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [31]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [32]:
B.size

16

In [33]:
np.linalg.det(B)

0.0


6. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [34]:
np.random.seed(42)

In [35]:
a = np.arange(0, 16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [36]:
np.sqrt(a.size)

4.0

In [37]:
C = a.reshape((4, 4))
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [39]:

C.shape == B.shape

True

In [40]:
D = 10 * C + B
print(D)

[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]


In [41]:

np.linalg.det(D)

-7.685903354004529e-25

In [42]:

D_inv = np.linalg.inv(D)
print(D_inv)

[[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


7. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [43]:
mask_positive = D_inv > 0
mask_negative = D_inv < 0

In [44]:
mask_positive = D_inv > 0
mask_negative = D_inv < 0

In [45]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122  14 302]]


Задание 2¶
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [46]:
a = np.array(
    [[1, 2, 3, 3, 1], 
    [6, 8, 11, 10, 7]]
).transpose()
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [47]:
mean_a = np.mean(a, axis = 0)
print(mean_a)

[2.  8.4]


Задание 3¶
Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [48]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 4
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [49]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
print(a_centered_sp)

8.0


In [50]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0


Задание 5**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве а. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации. В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив a. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [51]:
np.cov(a.T)[0, 1]

2.0